### ISSUE TITLE
compatibility php 7.4 array and not show notice or warnings

### ISSUE THREAD

**Issue by hormus** [BeProSoftware/bepro-listings#24]
https://github.com/BeProSoftware/bepro-listings/blob/master/admin/bepro_listings_admin.php#L790
$_POST=array();
or $_POST=array(array()); //For double array ;)

Array-style access of non-arrays https://www.php.net/manual/en/migration74.incompatible.php

**Comment by beyondprograms** [comment]
fixed in the latest version of BePro Listings 3.2.0001. Now offering PHP 8.0 compatibility.
